# Generated by Django 4.1.1 on 2022-10-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=180)),
                ('cause', models.CharField(max_length=180)),
                ('fromdt', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('todate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
