# Generated by Django 4.1.1 on 2022-11-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_leave_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='type',
        ),
    ]
